apiVersion: v1
kind: Service
metadata:
  labels:
    app: heejun-web
  name: heejun
  namespace: cnu-project1
  ports:
      protocol: TCP
      targetPort: 80
  selector:
    app: heejun-web
  type: LoadBalancer
